[project]
name = "bhu3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "piper>=0.14.5",
    "rapidfuzz>=3.14.3",
    "requests>=2.32.5",
    "sounddevice>=0.5.5",
    "vosk>=0.3.45",
]
